version: '3'
services:
  mariadb:
    image: mariadb:10.7
    container_name: aro-mariadb
    restart: always
    ports:
      - "13306:3306"
    env_file:
      - ./.env
    environment:
      TZ: Asia/Seoul
    volumes:
      - aro-mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: aro-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - aro-redis-data:/data

  app:
    build: .
    container_name: aro-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/${MARIADB_DATABASE}?serverTimezone=Asia/Seoul
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mariadb
      - redis

volumes:
  aro-mariadb-data:
  aro-redis-data: