spring:
  datasource:
    url: jdbc:mariadb://localhost:13306/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
